insert into users (id,
                   created_at,
                   updated_at,
                   email,
                   first_name,
                   last_name,
                   password,
                   phone,
                   second_name,
                   degree_id,
                   organization_id,
                   position_id,
                   rank_id) VALUES (
  1,
  '2018-07-05 00:00:00',
  '2018-07-05 00:00:00',
  'admin@admin.com',
  'Суперпользователь',
  'Суперпользователь',
  null,
  null,
  'Суперпользователь',
  1,
  1,
  1,
  1
);